<?php
// Automatically Generated by TestLink Installer - Sat, 09 Apr 16 16:08:09 +0000
define('DB_TYPE', 'mysql');
define('DB_USER', 'username');
define('DB_PASS', 'password');
define('DB_HOST', 'localhost');
define('DB_NAME', 'username');
define('DB_TABLE_PREFIX', 'testlink');
